### ISSUE TITLE
Plasmo Voice capture reverb

### ISSUE THREAD

**Issue by thedocruby** [vlad2305m/Sound-Physics-Fabric#23]
Issue for tracking the development of mic capture reverb with Plasmo Voice client

**Comment by Apehum** [comment]
I've made a working prototype but it needs polishing. 

Demo: https://youtu.be/wjrzTiDVztI

I've copied functions onPlaySound and evaluateEnvironment and renamed them to onPlayReverb and evaluateReverb. They are not much different from the original, the only difference is that directGain is set to 0.0f so that it outputs only reverb, without the original signal. Output is affected not only by reverb, but also by everything else, because I'm not sure what needs to be removed so that only reverb is calculated. 

It will be nice to make it so that onPlayReverb returns true or false, depending on whether there is reverb or not. If that is possible. Also, evaluateReverb should output only reverb. 

Test branch for Plasmo Voice: https://github.com/plasmoapp/plasmo-voice/tree/1.18-capture-reverb
 https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.9-test-client

Sound Physics Fork: https://github.com/Apehum/Sound-Physics-Fabric/tree/pvoice-reverb
 https://github.com/Apehum/Sound-Physics-Fabric/releases/tag/0.4.1-capture-pre

**Comment by thedocruby** [comment]
@Apehum Nice work! Seems to work well in the demo! When I ger time I will see what I can do about polishing the code on my end. Thanks so much for all your help!

**Comment by thedocruby** [comment]
Fixed with b5de7df43fa5b49ddc4f7df4ad27fa2372576680

**Comment by thedocruby** [comment]
Ran into some issues, reopening until publicly released
