### ISSUE TITLE
Jukeboxes unaffected by sound dampening

### ISSUE THREAD

**Issue by SleepyTonia** [vlad2305m/Sound-Physics-Fabric#38]
I'm mostly putting this here as a feature proposal since jukeboxes are deliberately made louder than anything else, but I think it would be a great addition if they could sound a bit more… immersive and accurate I guess?

**Comment by thedocruby** [comment]
I noticed this is a problem for Note Blocks as well. @vlad2305m can you look into this? Outside my area of expertise.

**Comment by vlad2305m** [comment]
This is intentional by sonic so that your noteblock mess in the walls, alarm, whatever... doesn't stop working. A setting for ignored sounds, or a setting for skipping occlusion can solve this.
@thedocruby 
https://github.com/vlad2305m/Sound-Physics-Fabric/blob/4a116d466ad86cb753966e7af32260f04a3f6bf9/src/main/java/com/sonicether/soundphysics/SoundPhysics.java#L207
Here is the statement. Perhaps just extract records to another `if` below and give them direct pass.
