### ISSUE TITLE
incobatible with iris

### ISSUE THREAD

**Issue by KlaraChaos** [vlad2305m/Sound-Physics-Fabric#46]
game crashed on startup and it shows that's its iris fault but after removing the sound mod everything started fine 

crash log
https://pastebin.com/peZLJkPL

modpack i used was another quality modpack 2

**Comment by thedocruby** [comment]
Unfortunately this is simply not a problem with SoundPhysics, and more likely the game just didn't start correctly and needed to be started again. However, because of the obscene amount of mods, i cant rule out the possibility of any mod conflict, but i can guarrantee that SoundPhysics was not directly involved. I would say that it might be possible if Iris used ClothConfig or AutoConfig for it's config screen, but I know for a fact that it does not. Keep in mind that I am also an Iris contributor and have been with the project for over a year.

Consider posting a more detailed issue report on the Iris github [here](https://github.com/IrisShaders/Iris/issues).
